flamingbird:
  reporter:
    instances:
      - name: error
        url: https://open.feishu.cn/open-apis/bot/v2/hook/34dcdea9-608b-444d-b936-300da0486bee
        type: feishu
      - name: stock
        url: https://open.feishu.cn/open-apis/bot/v2/hook/34dcdea9-608b-444d-b936-300da0486bee
        type: feishu
    enabled: true
spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 4396